#[[d1_databases]]
#binding = "DB" # i.e. available in your Worker on env.DB
#database_name = "hono-blog"
#database_id = "299892c2-6e11-4834-8686-3c0855c199a8"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hono-blog-demo"
database_id = "c1ec051a-3e19-4c89-92fa-bdc2b3f69e1c"